const AryanagarPanchayat2026 = {
  body: [
    "## Introduction",
    "On 20 September 2026, a social panchayat in Aryanagar village, Hisar district, meeting with about a thousand villagers present, resolved to impose a social boycott on couples from the same village who marry each other, and on the families who support them. Social media discussion of the meeting, and some headlines, have widened this into a general ban on love marriage. The panchayat's own resolution, and the case that prompted it, were narrower than that.",

    "## What the Panchayat Actually Resolved",
    "The meeting followed three marriages in the village in recent months that families had not approved of: two between couples of different castes, one between a couple of the same caste. What the three had in common was not caste but village: in each case, the bride and groom were both from Aryanagar. The resolution addresses exactly that, a man and woman from the same village marrying each other, under the same custom that treats co-villagers as siblings, the same logic [khap institutions elsewhere apply to same-gotra marriage](/research/khap-panchayat-system).",
    "::list:Couples who marry within the same village face social boycott and are barred from living in the village.|Families who support such a marriage, and others who back the couple, face the same boycott.|A committee was proposed to canvass household-level support for enforcing the decision.",
    "Elected sarpanch Ratan Singh has since clarified that the statutory Gram Panchayat had no part in the decision: it was taken by a separate social panchayat, a community assembly without the elected body's legal authority. Hisar's Superintendent of Police, Siddhant Jain, said police would monitor the situation and ensure the couples' safety, and that no one would be permitted to take the law into their own hands. Advocate Kamal Anand has pointed out that adults have a fundamental right under Article 21 of the Constitution to choose their own partner, and that a social boycott order carries no legal force.",

    "## Conclusion",
    "Same-village marriage restrictions like this one are not simply about administrative boundaries. In a Haryana Jat village historically settled by a concentrated set of founding lineages, the village itself can function as a dense, locally remembered kinship network, not unlike a gotra, so a prohibition on marrying within it can rest on specific genealogical knowledge rather than geography alone. It also prevents a situation where a person's maika and sasural become the same village, which matters for how households, inheritance and family ties are organised, not only for who is related to whom. That such a system is built to avoid marriage within known kinship networks is a claim about social structure, established through genealogy and oral history; that it produces a measurable genetic advantage is a separate claim, requiring population-genetic evidence this Archive has not examined here. Reporting the Aryanagar resolution as a ban on love marriage in general drops that reasoning, reducing a specific, locally understood restriction to a general taboo.",
  ],
  sources: [
    "The Tribune. Hisar panchayat prohibits same-village marriages. 21 September 2026. https://www.tribuneindia.com/news/haryana/hisar-panchayat-prohibits-same-village-marriages/ (Aryanagar, Hisar; social panchayat resolution against same-village marriage and social boycott; sarpanch Rattan Singh and BJP leader Hanuman Verma named among those present; the village-as-family rationale for treating co-villagers as siblings).",
    "The Tribune. Hisar village panchayat passes resolution against love marriages, announces social boycott. 21 September 2026. https://www.tribuneindia.com/news/haryana/hisar-village-panchayat-passes-resolution-against-love-marriages-announces-social-boycott/ (same meeting; three same-village marriage cases as the trigger; references a comparable Jind khap precedent covering same-village, neighbouring-village and same-gotra marriage).",
    "Dainik Tribune. A village panchayat in Hisar issues a decree against love marriages, announcing a social boycott of such couples. 21 September 2026. https://www.dainiktribuneonline.com/news/nation/a-village-panchayat-in-hisar-issues-a-decree-against-love-marriages-announcing-a-social-boycott-of-such-couples/ (trigger detail; boycott extended to supporting families; youth pushback on social media. Note: this and both Tribune reports above date the meeting to \"Sunday, 21 September\", but 21 September 2026 was a Monday; 20 September was the Sunday that week, matching Inkhabar's dating below, which this article follows).",
    "Inkhabar. Hisar lover marriage social boycott: know what SP Siddhant Jain and advocate Kamal Anand said on the ban. Published in the days following the 20 September meeting. https://www.inkhabar.com/haryana/hisar-lover-marriage-social-boycott-know-what-sp-siddhant-jain-and-advocate-kamal-anand-said-on-ban-292982 (meeting date and attendance of about 1,000 villagers; SP Siddhant Jain on police monitoring and the couples' safety; Advocate Kamal Anand on Article 21 and the boycott's lack of legal force; sarpanch Ratan Singh's clarification that the elected Gram Panchayat had no role).",
    "Rashtriya Ujala. Sarpanch's clarification on the love marriage controversy in Haryana. 23 September 2026. https://www.rashtriyaujala.com/2026/09/23/sarpanchs-clarification-on-love-marriage-controversy-in-haryana/ (sarpanch Ratan Singh stating the decision was taken by a social panchayat, not the elected Gram Panchayat).",
  ],
};

export default AryanagarPanchayat2026;
