const DelhiVillages = {
  body: [
    "## Introduction",
    "Long before Delhi became India's capital, it was a landscape of villages -- agricultural commons, grazing grounds, sacred groves, and settlements bound together by kinship and customary governance. Local and community memory holds that the region once comprised three hundred and sixty villages, organized under a khap system with Palam recognized as the head or chief khap, a tradition some trace back to the year 601. Whether or not every detail of this account can be independently verified, it points to something documented historians increasingly take seriously: Delhi's urban sprawl did not arrive on empty ground. It absorbed an inhabited landscape, village by village, over more than a thousand years.",

    "## The Khap Tradition: Three Hundred and Sixty Villages",
    "In the oral history and popular memory of the region's agrarian communities, the number three hundred and sixty recurs as a description of how many villages once made up the wider Delhi countryside, organized under a khap -- a customary council structure historically used by Jat and other landholding communities across the Delhi-Haryana-western Uttar Pradesh belt to govern land, marriage, and dispute resolution across clusters of villages. Within this tradition, Palam is remembered as the head or senior khap, the village whose council carried precedence among the wider group.",
    "These figures and roles are transmitted primarily through community memory rather than a single surviving written register, which is true of most khap traditions across North India. That does not make them unimportant -- it makes them exactly the kind of evidence that requires careful documentation before it disappears, the same argument this Archive has made about zamindari estates and family lineages elsewhere in North India. What is independently verifiable is that the broader number of historic village settlements in the Delhi region sits in a comparable range: oral-history researchers documenting Delhi's village heritage have catalogued roughly three hundred such settlements, of which roughly a hundred and thirty-five were formally absorbed into the city as recognized urban villages. The traditional count of three hundred and sixty and these documented figures are not identical, but they describe the same underlying reality through two different kinds of record -- one carried in memory, the other compiled from land and revenue documentation.",

    "## Colonial Lal Dora and the Redrawing of Village Boundaries",
    "The first major rupture in how these villages were administered came in 1908, when the British colonial administration drew what came to be known as the lal dora -- literally the 'red line' -- around each village's residential core, separating it on paper from the surrounding agricultural land. This single administrative act created a legal distinction that still shapes Delhi today: land inside the lal dora was, and remains, subject to different building and planning rules than land outside it, a distinction that survived the transition from colonial to independent India even as the agricultural land around most villages was acquired, planned, and built over.",

    "## From Inhabited Landscape to Imperial Capital",
    "When King George V announced at the 1911 Delhi Durbar that the capital of British India would move from Calcutta to Delhi, the decision set in motion the clearance and absorption of numerous existing settlements. Villages including Raisina, Malakpur, Rakabganj, and Wazirpur gave way to the construction of New Delhi's government quarter, while other settlements were displaced or restructured to accommodate the new imperial city. Colonial planners simultaneously began classifying certain ruins and monuments within this landscape as heritage worth preserving -- the gardens later known as Lodi Garden are a frequently cited example -- even as the living villages around those same monuments were treated as obstacles to be cleared rather than communities to be protected. This selective memory, preserving stone while displacing people, set a pattern that would repeat through the twentieth century.",
    "The villages around Delhi were not passive bystanders to this history. Many participated in the 1857 uprising against the East India Company, and the British administration's response included sustained surveillance and repression of the surrounding rural areas in the decades that followed -- a history that further entangled these settlements with the political fate of the capital being built around them.",

    "## Partition and the Postcolonial Expansion",
    "The 1947 Partition brought a second wave of demographic upheaval. Hindu and Sikh refugees arrived in large numbers even as many of the city's Muslim residents departed, and historic monuments across Delhi were pressed into service as emergency shelters for displaced families. Resettling this population, alongside the steady southward growth of the city through the 1950s toward areas like Hauz Khas and Mehrauli, required still more agricultural land to be acquired and converted into planned colonies and government institutions. Village commons -- grazing land, water systems, fuel-gathering grounds -- were enclosed and converted into private or institutional property, frequently without compensation or planning that accounted for the villagers who depended on them.",

    "## The Urban Village: Neither Rural Nor Urban",
    "What survived this century of acquisition was not the village as it had existed, but a distinct and somewhat anomalous category that planners now call the 'urban village': a settlement whose agricultural land has been absorbed into the city around it, while its residential core -- still defined by the colonial-era lal dora -- retains a different legal and planning status. Researchers documenting this category, including oral-history projects working across roughly three hundred such settlements, describe urban villages as a kind of internal periphery: neither served with the infrastructure planning normally extends to urban areas, nor protected with the land rights and heritage recognition that might come with formal rural status. Social institutions that once anchored community life, such as the chaupal -- a village's open gathering space for discussion and dispute resolution -- have in many cases fallen into neglect as the social structures that sustained them eroded.",

    "## Case Studies in Loss and Adaptation",
    "The village of Devli, on the Aravalli ridge between Sangam Vihar and Chattarpur, illustrates how slowly and unevenly this transition has unfolded. Devli was not formally declared an urban village until 2019, despite decades of residential development around it. Its Mahamai shrine, established around 1918-19 during a fever epidemic when villagers could no longer carry their dead to the Yamuna for cremation, served as an unrestricted community sacred site for roughly a century before access restrictions began in 2018. A 1996 Supreme Court directive requiring surplus ridge land to be transferred to forest protection, followed by a 2020 Ministry of Housing order placing village common (Gaon Sabha) land under Delhi Development Authority control, has meant that forest guards now condition the community's annual worship at its own shrine on official permission.",
    "Other ridge villages illustrate different outcomes. At Khampur Raya, the village deity's shrine now sits enclosed within a luxury housing complex built through a public-private redevelopment, and entry requires identity verification at the gate. Shadipur, declared an urban village as early as 1966, has by contrast managed to negotiate continued community access to its sacred sites despite the same institutional pressures -- a reminder that the outcome for any given village has depended heavily on local negotiation, not just policy.",

    "## When Neglect Becomes Tragedy",
    "The consequences of treating lal dora areas as a permanent regulatory grey zone are not only cultural. In the urban villages of Said-ul-Ajaib near Saket and Hauz Rani near Malviya Nagar, buildings that began as family homes were, by the 1990s, converted into dense rental housing, guest houses, cafes, and clinics -- often without the floor-count approvals, fire certifications, or electrical and structural standards that would apply outside the lal dora boundary. Lanes built for residents and cattle now carry cars, delivery vehicles, and the occasional fire engine that cannot fit through them. A building collapse in Said-ul-Ajaib and a guesthouse fire in Hauz Rani have each been linked to this accumulated regulatory gap. These urban villages nonetheless continue to provide affordable housing for students, migrants, and workers, and a density of small business and food culture unavailable elsewhere in the city -- which is precisely why documenting and fixing, rather than simply condemning, their built environment matters.",

    "## Why This Matters for Khap and Community History",
    "Delhi's urban villages sit at the same intersection that motivates this Archive's broader work on zamindari estates, family lineages, and rural heritage elsewhere in North India: a documented record of land, authority, and community life that is disappearing faster than it is being recorded. Whether the figure is the three hundred and sixty villages remembered in khap tradition, the roughly three hundred catalogued by oral-history researchers, or the hundred and thirty-five recognized today as urban villages, the underlying lesson is the same one this Archive has drawn from the Pilania zamindars and the Dalal family of Kuchesar: when a community's history survives mainly in memory and in buildings rather than in a single written archive, every demolished house, restricted shrine, or undocumented khap genealogy is a permanent loss, not a recoverable one.",

    "## Conclusion",
    "Delhi's transformation from a countryside of villages -- however many there were at any given point -- into a metropolis of more than thirty million people did not erase those villages so much as fold them into the city on unequal terms: their farmland taken, their commons enclosed, their legal status frozen in a colonial-era boundary line, and their own institutions, from khap councils to chaupals to neighborhood shrines, left to survive or disappear depending on local circumstance. Recovering and documenting both the oral traditions, such as the khap memory of Palam's historic precedence, and the administrative record, such as the lal dora and the urban village category it created, is necessary to understand how Delhi actually became what it is today.",
  ],
  sources: [
    "DevRay Talks. Posh colonies ke neeche dabi hain purani zindagiyan -- Delhi ke gaon ka sach jo koi nahi batata. YouTube. https://www.youtube.com/watch?v=wVZMtDSAcr0 (source for the khap tradition of 360 villages and Palam as head khap, presented here as community oral history, not independently verified academic record).",
    "Newslaundry. (2026, April 13). Delhi's Ridge Was Once a Shared Sacred Landscape; Now Faith Needs Permission. https://www.newslaundry.com/2026/04/13/delhis-ridge-was-once-a-shared-sacred-landscape-now-faith-needs-permission",
    "Singhal, Puneet Singh. (2026, June 17). What Delhi's Villages Teach Us About Development. Development Studies Association. https://www.devstud.org.uk/2026/06/17/what-delhis-villages-teach-us-about-development/",
    "Singhal, Puneet Singh. What Delhi Owes Its Urban Villages: Saket Building Collapse, Malviya Nagar Fire. National Herald India. https://www.nationalheraldindia.com/opinion/what-delhi-owes-its-urban-villages-saket-building-collapse-malviya-nagar-fire",
    "The Quint. Delhi's Villages, City Expansion, and Planning Heritage. https://www.thequint.com/lifestyle/art-and-culture/delhi-villages-city-expansion-and-planning-heritage",
  ],
};

export default DelhiVillages;
