const KhapPanchayat2026 = {
  body: [
    "## Introduction",
    "In August 2026, two meetings of the Naugama Khap at Ramrai village in Jind district, Haryana, drew national attention. The first, held at the start of the month, passed a set of resolutions on marriage, clothing and social conduct, and produced a remark about how daughters should sit on motorcycles that circulated widely on social media. The second, three weeks later, was the khap's first women's mahapanchayat, presided over by the national president of the women's wing of the Sarv Jatiya Sarv Khap Panchayat.",
    "This article sets out what was actually decided at both, distinguishes the resolutions of the assembly from the remarks made before it, and places them alongside the wider record of khap decisions in Haryana over the past decade. It does so because the public argument about these institutions has largely been conducted through a single circulated clip, and because an accurate record supports better criticism than a fragmentary one -- including, where the record warrants it, criticism of the khap.",
    "Readers should note at the outset that the record does not resolve neatly in either direction. The most widely reported detail of the August meeting was indeed a personal remark rather than a resolution. But the meeting also adopted formal, enforceable decisions restricting marriage and dress, complete with an enforcement committee empowered to impose penalties. Both facts belong in the account.",

    "## What a Khap Panchayat Is",
    "A khap is a customary council structure historically used by Vedic Jāṭ and other landholding communities across the Delhi-Haryana-western Uttar Pradesh belt to govern land, marriage, and dispute resolution across clusters of villages. A khap panchayat is the assembly through which such a body deliberates; a mahapanchayat is a larger gathering convened across several khaps or many villages. The Naugama Khap comprises twenty-one villages across Jind and Hisar districts.",
    "Panchayat systems of this kind long predate the Mughal period. Different communities across the subcontinent have historically maintained their own systems of internal rule-making and social regulation, adapting them over time. Contemporary khap assemblies draw participants from a range of backgrounds -- retired government employees, senior community members, youth representatives and, increasingly, women representatives -- and take up matters ranging from marriage and social disputes to employment, education, substance abuse and the welfare of the elderly. (Community account: this description of composition reflects participant testimony rather than a published membership register, and is recorded here as a ground report.)",

    "## The Ramrai Meeting, 1-2 August 2026: What Was Actually Resolved",
    "Accounts differ slightly on the date -- ThePrint places the meeting on 1 August 2026, while The Tribune reported it as 2 August -- but the substance is consistent across reports. The meeting was held at Ramrai and chaired by Jaiveer Singh Lohan, pradhan of the Naugama Khap, with Umed Singh Jaglan as spokesperson.",
    "The assembly adopted the following resolutions. It imposed a lifetime boycott on couples who marry in violation of khap norms, providing that such a couple would not be permitted to enter their native villages, with the prohibition extending across the khap's twenty-one villages. It restricted marriages within the same village, between neighbouring villages, and within the same gotra. It prohibited what it described as provocative clothing for girls. It banned obscene songs at social functions and assumed authority to impose fines. It resolved against live-in relationships and demanded the repeal of the legal provisions recognising them. It offered a reward of five thousand rupees to informants reporting drug trafficking. To give effect to these decisions it constituted a twenty-one member enforcement committee, alongside village-level committees, empowered to oversee implementation and determine penalties.",
    "These are not incidental measures. A boycott enforced across twenty-one villages, backed by a committee with the power to set penalties, is a serious sanction, and the restrictions on same-gotra and same-village marriage engage directly with the law discussed later in this article. Any honest account of the August meeting must begin here rather than with the motorcycle.",

    "## The Remark and the Resolution",
    "The detail that travelled furthest was not among the resolutions. Virender Dhull, a khap member and a teacher at a Jat school in Jind, said in the course of the meeting that daughters should not sit astride motorcycles behind their fathers as sons do, and that phones should be confiscated and destroyed. This was reported, and circulated, as a khap diktat.",
    "It was a personal remark made during deliberation, not a decision of the body, and on that narrow point the criticism was misdirected. A khap panchayat is a deliberative assembly in which individuals speak, disagree and are sometimes overruled; the resolutions it adopts are distinct from the statements made in reaching them. The same distinction is applied without difficulty to remarks in legislative debate, which are not treated as statute.",
    "Two qualifications matter, however, and both cut against a purely exculpatory reading. First, Dhull did not retract. Approached by reporters, he said he stood by his views and that expressing his opinion was his right. Second, this Archive has not been able to locate any published statement by the khap leadership clarifying that the motorcycle remark carried no official standing. Such a clarification has been described in community accounts, but it does not appear in the reporting reviewed here, and it is recorded as unverified rather than presented as established fact. The distinction between remark and resolution is real and documented; a formal disavowal is not.",

    "## The Youth Response",
    "The response from young Haryanvis was substantial and took place largely on Instagram. More than thirty thousand videos appeared under the hashtags #khap and #khapp, drawing in creators including Paras Yadav, Geeta Dhanda and the rapper Rahul Fazilpuria. Much of the response challenged the khap's authority over women's personal choices, and a recurring argument invoked Haryana's sex ratio -- reported at 879 girls per 1,000 boys -- to question the standing of the institution to legislate on the conduct of daughters.",
    "This was not commentary from outside the community. It came from within it, from the generation the khap's resolutions were addressed to, and it is the most significant feature of the episode. Framing the argument as rural tradition against urban outsiders does not survive contact with who was actually objecting.",

    "## Children, Phones, and Whose Concern It Is",
    "The second element of Dhull's remark -- that children spend excessive time on phones -- was widely treated as self-evidently parochial. That framing does not survive examination of the record elsewhere.",
    "On 26 August 2026, three days after the women's mahapanchayat at Ramrai, Meta announced a settlement of up to seventeen billion dollars with a bipartisan coalition of US state attorneys general, ending a federal trial in Oakland, California. The states had argued that Facebook and Instagram were deliberately designed to hook children, that the company misled the public about the resulting harm, and that it improperly collected data from children under thirteen in violation of the Children's Online Privacy Protection Act. The settlement, which remains subject to approval by Judge Yvonne Gonzalez Rogers, requires Meta to limit users under eighteen to two hours per day, to block access between midnight and six in the morning, to restrict notifications during school hours, to offer a chronological rather than algorithmic feed that parents may set as the default, and to remove likes and reactions from view for minors. Meta continues to deny wrongdoing.",
    "The specific proposal -- that a child's phone should be confiscated and destroyed -- is not what American regulators arrived at, and the difference between a household prohibition and a regulated design standard is substantial. But the underlying concern about adolescent social media use is demonstrably not confined to village elders in Haryana. Dismissing it as rural backwardness, in the same month that the largest such settlement in the sector's history was announced, is not an argument.",
    "Nor does modernity distribute itself along the lines the coverage assumed. Wearing shorts or a ghoonghat, how one sits on a motorcycle, how much time one spends on a phone -- none of these is on its own evidence of a person's judgement or its absence.",

    "## The Women's Mahapanchayat, 23 August 2026",
    "On 23 August 2026, the Naugama Khap convened its first women's mahapanchayat at the khap chabutra in Ramrai. It was presided over by Santosh Dahiya, national president of the women's wing of the Sarv Jatiya Sarv Khap Panchayat. Reporting is explicit that the gathering was convened in direct response to the social media backlash against the August resolutions, and that the earlier meeting had issued restrictions on personal matters without female representation.",
    "The mahapanchayat adopted resolutions opposing love marriages, live-in relationships, the dowry system, gun culture, and offensive or objectionable content. Santosh Dahiya described it as organised by women to address directly the key issues affecting society, naming live-in relationships, love marriages, dowry and gun culture. A twenty-one member committee was constituted to visit the villages, explain the resolutions and seek public support. Reporting notes that the resolutions do not override laws or constitutional rights applicable across India.",
    "The significance of this meeting is genuine but should not be overstated in either direction. It is the first occasion on which women of the constituent villages deliberated in their own right under the khap's structure, and that is a real institutional change in a body that had issued directives on women's conduct without them. It is also true that the assembly was convened under pressure, and that its resolutions on love marriage and live-in relationships reaffirmed rather than revised the positions taken three weeks earlier. Presenting the mahapanchayat as evidence of liberalisation misreads it; presenting it as meaningless misreads it equally.",

    "## The Wider Record of Khap Decisions",
    "The proposition that recent khap meetings in Haryana have concerned themselves principally with women's clothing and marriage does not survive examination of the fuller record.",
    "On 25 July 2026, a sarva khap mahapanchayat at the historic Chaubisi Chabutra in Meham drew representatives of more than seventy khaps from within and outside Haryana. It resolved that Haryanvi artists found promoting drug abuse, obscenity or vulgar content on social media would face action at both social and legal levels, with cases reported to the police. It was also the first Sarva Khap mahapanchayat at Meham at which hookah was neither served nor smoked, and the body resolved to bar hookah from its future meetings as an anti-smoking measure -- a decision that currently binds only the Meham Chaubisi sarva khap panchayat.",
    "Comparable measures are documented earlier. Khap bodies have banned liquor sales across clusters of villages, restricted DJ sound systems and rash driving at weddings, and a mahapanchayat drawing representatives of over a hundred khaps from Haryana, Delhi and Uttar Pradesh took a public stand against female foeticide, demanding that murder cases be registered against those responsible. Community accounts additionally describe a Dahiya Khap mahapanchayat in 2017 adopting restrictions on alcohol, DJ systems, the display of weapons and conspicuous wedding expenditure, together with campaigns against intoxicants and female foeticide; this Archive was unable to locate published reporting confirming the specific resolutions of that gathering, and it is recorded here as a ground report pending documentation.",
    "Read together, this is a record of social reform directed substantially inward -- at wedding expenditure, intoxicants, the celebration of weapons, obscenity in popular music, and female foeticide. These measures attract a small fraction of the coverage given to decisions about women's conduct.",

    "## Community Autonomy and Its Limits",
    "A recurring argument holds that communities have historically maintained their own internal rules, that one community does not ordinarily interfere in another's internal regulation, and that a person who disagrees remains free not to follow those rules or to leave.",
    "The first two propositions describe accurately how plural social orders have functioned across the subcontinent. The third requires more care, and the August resolutions illustrate why. A lifetime boycott barring a couple from entering their native villages, enforced across twenty-one villages by a committee empowered to set penalties, is not a rule one can simply decline to follow while remaining in place. It is designed to make exit the only option, and to make that option costly. An argument from consent is only as strong as the exit it presupposes, and the practical availability of exit varies with age, gender, economic independence and outside support.",
    "This is where honest disagreement should turn: does a given rule respect the consent, liberty and safety of the person subject to it? Where it does, criticism of the institution as such is misplaced. Where it does not, the criticism is warranted and should be directed specifically at that rule.",

    "## Honour Killings and the Legal Framework",
    "Two distinct claims are frequently conflated here, and the distinction matters.",
    "The first is that the murder of a son or daughter by their own family is a criminal act, prosecuted as such. Attributing such a killing to an entire khap as its official decision, absent evidence that the body resolved upon it, is not supported by the record in most reported cases, and the conflation is unfair to assemblies that took no such decision.",
    "The second claim is narrower and well documented: that khap panchayats have in specific instances interfered in marriages, particularly across gotra and village lines, and that the Indian courts have held such interference unlawful. In Shakti Vahini v. Union of India (2018), the Supreme Court held that any assembly gathering to condemn a marriage between two consenting adults is illegal, and issued preventive, remedial and punitive directions binding on state authorities. The Law Commission of India had earlier examined the question in its report on interference with the freedom of matrimonial alliances. The conviction in the Manoj-Babli case remains the reference point for khap-linked prosecution.",
    "This bears directly on the August resolutions. A decision restricting marriage within the same gotra or the same village, enforced by boycott, is precisely the category of collective action Shakti Vahini addressed. Whatever the merits of gotra exogamy as a customary norm -- and it is a norm with a long history and its own internal rationale -- a resolution of this kind sits in tension with binding precedent, and a defence of the khap that does not engage with that precedent is incomplete in the same way as a criticism resting on a single clip.",

    "## What Honest Criticism Would Require",
    "The standard proposed here is symmetry, not deference. Treating every khap decision as legitimate because the institution is old is as unserious as treating every khap as illegitimate because a clip circulated. Both substitute a general verdict for the specific inquiry a particular decision requires.",
    "An honest criticism would identify the decision at issue, establish that it was in fact a decision of the body rather than a remark made before it, set out its full context, and ask whether it respects the consent, freedom and safety of those subject to it. Applied to August 2026, that method yields a mixed verdict: the motorcycle remark was misreported as a diktat, and the boycott and clothing resolutions were real, consequential and legally vulnerable. Both findings follow from the same standard.",
    "Understanding how these institutions function is genuinely harder from the outside, and firsthand familiarity with a community's social structure is an advantage in interpreting what one sees. But familiarity is not endorsement, and distance is not objectivity. The remedy for a partial view is a fuller record, not a competing claim of standing -- particularly when, as here, much of the criticism came from within the community itself.",

    "## Conclusion",
    "August 2026 offers an unusually complete test case. Within a single month one khap passed enforceable restrictions on marriage and dress, produced a widely circulated remark that was not a resolution at all, faced a substantial revolt from its own younger generation on social media, and convened the first women's mahapanchayat in its history -- which then reaffirmed the contested positions rather than revising them. In the same weeks, a mahapanchayat of seventy khaps at Meham resolved against drug-promoting and obscene content and gave up hookah at its own gatherings, and a settlement of up to seventeen billion dollars in the United States vindicated, in a very different register, the proposition that adolescent social media use warrants concern.",
    "None of these facts is fully captured by the clip that travelled furthest, and none is captured by a blanket defence either. This Archive's position is that the whole record belongs in the account: the resolutions and the remark, the reform measures and the boycott, the first women's assembly and the reason it was called, and the case law that constrains what any such body may lawfully decide about the marriages of consenting adults. Documenting an institution accurately is a precondition for criticising it usefully.",
  ],
  sources: [
    "The Tribune. Haryana's Naugama khap passes resolution to boycott couples violating 'norms'. https://www.tribuneindia.com/news/haryana/naugama-khap-passes-resolution-to-boycott-couples-violating-norms/ (meeting at Ramrai dated 2 August 2026; Jaiveer Singh Lohan as pradhan, Umed Singh Jaglan as spokesperson; resolutions on lifetime boycott, same-village, neighbouring-village and same-gotra marriage, provocative clothing, obscene songs and fines, live-in relationships, Rs 5,000 drug informant reward, and the twenty-one member enforcement committee).",
    "The Tribune. Haryana: Naugama Khap orders lifetime boycott of couples violating marriage norms. https://www.tribuneindia.com/news/haryana/haryana-naugama-khap-orders-lifetime-boycott-of-couples-violating-marriage-norms/",
    "ThePrint. Haryana khap wants daughters off phones, not astride two-wheelers. Gen Z films its reply on Insta. https://theprint.in/india/haryana-khap-wants-daughters-off-phones-not-astride-two-wheelers-gen-z-films-its-reply-on-insta/3011850/ (meeting dated 1 August 2026; Virender Dhull's remarks and his statement that he stood by them; hashtag volumes, named creators, and the 879:1000 sex ratio figure).",
    "The Tribune. Facing youth backlash, Naugama khap calls first-ever women's mahapanchayat. https://www.tribuneindia.com/news/haryana/facing-youth-backlash-naugama-khap-calls-first-ever-womens-mahapanchayat/ (mahapanchayat of 23 August 2026 at the Naugama khap chabutra, Ramrai; Santosh Dahiya presiding; convened in response to youth backlash).",
    "ANI / Webindia123. 'Love marriages, live-ins not acceptable': Khap women's Mahapanchayat in Haryana's Jind, 23 August 2026. https://news.webindia123.com/news/Articles/India/20260823/4490145.html (resolutions on love marriage, live-in relationships, dowry, gun culture and objectionable content; twenty-one village committee; note that the resolutions do not override law or constitutional rights).",
    "The Tribune. Sarva khap mahapanchayat bans obscene, drug-promoting content by Haryanvi artists. https://www.tribuneindia.com/news/haryana/sarva-khap-mahapanchayat-bans-obscene-drug-promoting-content-by-haryanvi-artists/ (Meham Chaubisi Chabutra, 25 July 2026; more than seventy khaps; hookah neither served nor smoked and barred from future meetings).",
    "The Tribune. Khap bans liquor in 40 Dadri villages. https://www.tribuneindia.com/news/archive/features/khap-bans-liquor-in-40-dadri-villages-342090 (Sangwan Khap liquor prohibition across forty villages).",
    "ThePrint. Khap panchayats -- the role & history of a complex social institution in Haryana & western UP. https://theprint.in/india/khap-panchayats-the-role-history-of-complex-social-institution-in-haryana-western-up/613988/",
    "NPR. Meta, states agree to $17 billion settlement in child safety trial, 26 August 2026. https://www.npr.org/2026/08/26/nx-s1-5944781/meta-settlement-child-safety-lawsuit",
    "The Conversation. Changes to Facebook and Instagram are key part of Meta's $17B settlement with the states over harm to teens. https://theconversation.com/changes-to-facebook-and-instagram-are-key-part-of-metas-17b-settlement-with-the-states-over-harm-to-teens-290582 (settlement terms: two-hour daily limit for under-18s, midnight to 6am block, school-hours notification limits, chronological feed option, removal of visible likes for minors; approval pending before Judge Yvonne Gonzalez Rogers).",
    "Shakti Vahini v. Union of India, (2018) 7 SCC 192 (Supreme Court of India), holding that an assembly gathering to condemn a marriage between two consenting adults is unlawful, and issuing preventive, remedial and punitive directions to state authorities.",
    "Law Commission of India, Report No. 242: Prevention of Interference with the Freedom of Matrimonial Alliances (in the name of Honour and Tradition) (2012).",
    "State of Haryana v. Manoj and Babli (Karnal Sessions Court, 2010), the first conviction in India in a khap-linked honour killing case.",
    "GROUND REPORT (unverified) -- Composition of contemporary khap assemblies, including participation by retired government employees, youth representatives and women representatives, as described in community testimony. No published membership register was located.",
    "GROUND REPORT (unverified) -- A Dahiya Khap mahapanchayat in 2017 adopting restrictions on alcohol, DJ sound systems, display of weapons and conspicuous wedding expenditure, with campaigns against intoxicants and female foeticide. No published reporting confirming these specific resolutions was located.",
    "GROUND REPORT (unverified) -- A clarification by the Naugama Khap leadership that the remark concerning how girls sit on motorcycles carried no official standing. Described in community accounts; not found in the reporting reviewed for this article.",
  ],
};

export default KhapPanchayat2026;
