const KhapPanchayat2026 = {
  body: [
    "## Introduction",
    "In August 2026, two meetings of the Naugama Khap at Ramrai village in Jind district, Haryana, drew national attention. The first, held at the start of the month, passed a set of resolutions on marriage, clothing and social conduct, and produced a remark about how daughters should sit on motorcycles that circulated widely on social media. The second, three weeks later, was the khap's first women's mahapanchayat, presided over by the national president of the women's wing of the Sarv Jatiya Sarv Khap Panchayat.",
    "This article sets out what was actually decided at both, and distinguishes the resolutions of the assembly from the remarks made before it, because the public argument about these meetings has largely been conducted through a single circulated clip.",
    "Readers should note at the outset that the record does not resolve neatly in either direction. The most widely reported detail of the August meeting was indeed a personal remark rather than a resolution. But the meeting also adopted formal, enforceable decisions restricting marriage and dress, complete with an enforcement committee empowered to impose penalties. Both facts belong in the account.",

    "## What a Khap Panchayat Is",
    "A khap is a customary council of Jāṭ and other landholding communities across the Delhi-Haryana-western Uttar Pradesh belt, governing land, marriage and dispute resolution across clusters of villages; a mahapanchayat is a larger gathering convened across several khaps or many villages. The Naugama Khap comprises twenty-one villages across Jind and Hisar districts. Its fuller structure, history and relationship with the state are set out in [The Khap Panchayat: Origins, Structure, and How It Actually Works](/research/khap-panchayat-system); this article confines itself to what the Naugama Khap actually did at Ramrai in August 2026.",

    "## The Ramrai Meeting, 1-2 August 2026: What Was Actually Resolved",
    "Accounts differ slightly on the date (ThePrint places the meeting on 1 August 2026, while The Tribune reported it as 2 August), but the substance is consistent across reports. The meeting was held at Ramrai and chaired by Jaiveer Singh Lohan, pradhan of the Naugama Khap, with Umed Singh Jaglan as spokesperson.",
    "The assembly adopted the following resolutions:",
    "::list:A lifetime boycott on couples who marry in violation of khap norms, barring them from entering their native villages, with the prohibition extending across the khap's twenty-one villages.|Restrictions on marriage within the same village, between neighbouring villages, and within the same gotra.|A prohibition on what it described as provocative clothing for girls.|A ban on obscene songs at social functions, with authority to impose fines.|Opposition to live-in relationships, with a demand for repeal of the legal provisions recognising them.|A reward of five thousand rupees to informants reporting drug trafficking.",
    "To give effect to these decisions the assembly constituted a twenty-one member enforcement committee, alongside village-level committees, empowered to oversee implementation and determine penalties.",
    "These are not incidental measures. A khap commands no police and levies no tax, so [its authority rests entirely on social sanction](/research/khap-panchayat-system), which is why boycott is its characteristic penalty. A boycott enforced across twenty-one villages, backed by a committee with the power to set penalties, is a serious sanction. Any honest account of the August meeting must begin here rather than with the motorcycle.",

    "## The Remark and the Resolution",
    "The detail that travelled furthest was not among the resolutions. Virender Dhull, a khap member and a teacher at a Jāṭ school in Jind, said in the course of the meeting that daughters should not sit astride motorcycles behind their fathers as sons do, and that phones should be confiscated and destroyed. This was reported, and circulated, as a khap diktat.",
    "It was a personal remark made during deliberation, not a decision of the body, and on that narrow point the criticism was misdirected. A khap panchayat is a deliberative assembly in which individuals speak, disagree and are sometimes overruled, reaching decisions by consensus of those present rather than by counted vote; the resolutions it adopts are distinct from the statements made in reaching them. The [procedure is described in full here](/research/khap-panchayat-system). The same distinction is applied without difficulty to remarks in legislative debate, which are not treated as statute.",
    "Two qualifications matter, however, and both cut against a purely exculpatory reading. First, Dhull did not retract. Approached by reporters, he said he stood by his views and that expressing his opinion was his right. Second, per the author's own knowledge, the khap leadership offered such a clarification, though no published statement to that effect was located independently in the reporting reviewed here. The distinction between remark and resolution is real and documented; a formal disavowal is not.",

    "## The Youth Response",
    "The response from young Haryanvis was substantial and took place largely on Instagram. More than thirty thousand videos appeared under the hashtags #khap and #khapp, drawing in creators including Paras Yadav, Geeta Dhanda and the rapper Rahul Fazilpuria. Much of the response challenged the khap's authority over women's personal choices, and a recurring argument invoked Haryana's sex ratio (reported at 879 girls per 1,000 boys) to question the standing of the institution to legislate on the conduct of daughters.",
    "This was not commentary from outside the community. It came from within it, from the generation the khap's resolutions were addressed to, and it is the most significant feature of the episode. Framing the argument as rural tradition against urban outsiders does not survive contact with who was actually objecting.",

    "## The Women's Mahapanchayat, 23 August 2026",
    "On 23 August 2026, the Naugama Khap convened its first women's mahapanchayat at the khap chabutra in Ramrai. It was presided over by Santosh Dahiya, national president of the women's wing of the Sarv Jatiya Sarv Khap Panchayat. The meeting was conducted entirely by women, with the khap's male members seated behind them as observers. Reporting is explicit that the gathering was convened in direct response to the social media backlash against the August resolutions, and that the earlier meeting had issued restrictions on personal matters without female representation.",
    "The mahapanchayat adopted resolutions opposing love marriages, live-in relationships, the dowry system, gun culture, and offensive or objectionable content. Santosh Dahiya described it as organised by women to address directly the key issues affecting society, naming live-in relationships, love marriages, dowry and gun culture. A twenty-one member committee was constituted to visit the villages, explain the resolutions and seek public support. Reporting notes that the resolutions do not override laws or constitutional rights applicable across India. It sits within a wider mahila khap structure that has been convening since at least 2010, [described here](/research/khap-panchayat-system).",
    "This was a first for Naugama Khap, not for Haryana: Haryana's actual first mahila mahapanchayat was convened at Kandela in Jind in 2021, five years earlier, [with the fuller mahila khap history set out here](/research/khap-panchayat-system). What was new at Ramrai was that a single khap convened its own women's assembly under its own structure.",
    "The significance of this meeting is genuine but should not be overstated in either direction. It is the first occasion on which women of the constituent villages deliberated in their own right under the khap's structure, and that is a real institutional change in a body that had issued directives on women's conduct without them. It is also true that the assembly was convened under pressure, and that its resolutions on love marriage and live-in relationships reaffirmed rather than revised the positions taken three weeks earlier. Presenting the mahapanchayat as evidence of liberalisation misreads it; presenting it as meaningless misreads it equally.",

    "## Conclusion",
    "August 2026 offers an unusually complete test case. Within a single month, one khap passed enforceable restrictions on marriage and dress, produced a widely circulated remark that was not a resolution at all, faced a substantial revolt from its own younger generation on social media, and convened the first women's mahapanchayat in its history, which then reaffirmed the contested positions rather than revising them. None of this is fully captured by the clip that travelled furthest: the resolutions and the remark, and the khap's first women's assembly and the reason it was called, all belong in the same account.",
  ],
  sources: [
    "The Tribune. Haryana's Naugama khap passes resolution to boycott couples violating 'norms'. https://www.tribuneindia.com/news/haryana/naugama-khap-passes-resolution-to-boycott-couples-violating-norms/ (meeting at Ramrai dated 2 August 2026; Jaiveer Singh Lohan as pradhan, Umed Singh Jaglan as spokesperson; resolutions on lifetime boycott, same-village, neighbouring-village and same-gotra marriage, provocative clothing, obscene songs and fines, live-in relationships, Rs 5,000 drug informant reward, and the twenty-one member enforcement committee).",
    "The Tribune. Haryana: Naugama Khap orders lifetime boycott of couples violating marriage norms. https://www.tribuneindia.com/news/haryana/haryana-naugama-khap-orders-lifetime-boycott-of-couples-violating-marriage-norms/",
    "ThePrint. Haryana khap wants daughters off phones, not astride two-wheelers. Gen Z films its reply on Insta. https://theprint.in/india/haryana-khap-wants-daughters-off-phones-not-astride-two-wheelers-gen-z-films-its-reply-on-insta/3011850/ (meeting dated 1 August 2026; Virender Dhull's remarks and his statement that he stood by them; hashtag volumes, named creators, and the 879:1000 sex ratio figure).",
    "The Tribune. Facing youth backlash, Naugama khap calls first-ever women's mahapanchayat. https://www.tribuneindia.com/news/haryana/facing-youth-backlash-naugama-khap-calls-first-ever-womens-mahapanchayat/ (mahapanchayat of 23 August 2026 at the Naugama khap chabutra, Ramrai; Santosh Dahiya presiding; convened in response to youth backlash).",
    "ANI / Webindia123. 'Love marriages, live-ins not acceptable': Khap women's Mahapanchayat in Haryana's Jind, 23 August 2026. https://news.webindia123.com/news/Articles/India/20260823/4490145.html (resolutions on love marriage, live-in relationships, dowry, gun culture and objectionable content; twenty-one village committee; note that the resolutions do not override law or constitutional rights).",
    "ThePrint. Demand for equal pay, 50% quota in Parliament at Haryana's first mahila mahapanchayat. https://theprint.in/india/demand-for-equal-pay-50-quota-in-parlaiment-at-haryanas-first-mahila-mahapanchayat/624271/ (Kandela village, Jind, 18 March 2021, Haryana's first mahila mahapanchayat, five years before Ramrai).",
    "Author's own knowledge that Naugama Khap leadership clarified the motorcycle remark carried no official standing; no published statement to this effect was located independently.",
  ],
};

export default KhapPanchayat2026;
