const MandkolaMahapanchayat2026 = {
  body: [
    "## Introduction",
    "On 6 September 2026, the village of Mandkola in Palwal district, Haryana, hosted a mahapanchayat convened by the 52 Pal -- a federation of pals, the term used in this part of the Delhi-Haryana-western Uttar Pradesh belt for the intermediate tier between village and khap -- together with 36 biradaris, the diverse resident communities of the villages concerned. The organisers described it in advance as the first gathering of its kind: a Sarv Khap, Sarvajatiya and Sarvadharma mahapanchayat, meaning a supreme assembly open across khaps, across every community rather than one founding clan, and across religion. Invitations reportedly reached villages from Delhi to Agra and Aligarh, and reporting put attendance in the thousands, drawn from Haryana, Delhi, Uttar Pradesh and Rajasthan.",
    "The mahapanchayat was attended by sitting and former legislators, and its resolutions -- almost two dozen by most counts -- set detailed limits on wedding expenditure, dowry, engagement customs, death feasts, alcohol and DJ music at social functions, and established a three-tier committee structure to review compliance. This article sets out what was announced beforehand, who attended, what was actually resolved, and where this gathering fits within the wider structure and history of khap and pal institutions already documented on this Archive.",

    "## Sarv Khap, Sarvajatiya, Sarvadharma: What the Framing Means",
    "The organisers' own description of the event is worth taking seriously rather than treating as a slogan. A khap is classically constituted on gotra -- a body founded by and for a single descent group. A Sarv Khap is a federation across khaps: several khaps convening jointly, a question of scale rather than membership. A sarvajatiya body extends membership beyond the founding clan to the several communities resident in its villages, a distinction [set out in detail in this Archive's study of khap structure](/research/khap-panchayat-system). Mandkola's organisers claimed something broader again: sarvadharma, participation across religion as well as caste, with a Muslim social activist, Tayyab Hussain Ghasediya, named alongside the Dagar Pal leadership among those organising the gathering.",
    "Whether this is in fact unprecedented, as the organisers claimed, is not something this Archive can verify from the reporting reviewed. What can be said is that it is a real, present-day instance of the widening pattern already documented elsewhere on this site: khap-derived institutions extending their membership outward from the founding clan, as at Naugama Khap, or convening across dozens of constituent bodies, as at the Meham sarva khap mahapanchayat of July 2026. Mandkola's claim to interfaith participation would, if accurate, extend that pattern a step further than either of those examples.",

    "## The Meeting: Who Attended",
    "Reporting names a substantial number of political figures among those present, in addition to community and pal leadership. Gaurav Gautam, Minister of State in the Haryana government holding the Youth Empowerment and Entrepreneurship and Sports portfolios and the sitting MLA for Palwal -- the constituency in which Mandkola sits -- attended and addressed the gathering, stating that development alone is not sufficient for a society to progress, and that curbing social evils and unnecessary expenditure is equally necessary. Also named in reporting were Uday Bhan, a former president of the Haryana Congress; Raghuveer Singh Tewatia, MLA; and Karan Singh Dalal, a five-time MLA and former Haryana minister who represented Palwal before losing his seat in the 2024 assembly election. Reporting also names Praveen Dagar as a former MLA in attendance, though this Archive notes that other sources identify a Praveen Dagar as the sitting MLA for the neighbouring Hathin constituency; this may be the same or a different individual, and the discrepancy is recorded here rather than resolved.",
    "No Member of Parliament is named as present in any of the reports reviewed for this article. Community-side attendance included Chaudhry Dharmveer Dagar and Arun Jeldar, both identified in different reports as presiding over or leading the 52 Pal body, and Vinod Sharma, president of the district Brahmin Sabha. A follow-up wave of reporting two days later recorded the resolutions being publicly welcomed by the presidents of the district Bar Association, a farmers' front, a trade federation, an employees' union, the local Jain community, and a garment traders' association -- an unusually broad cross-section of civic bodies for a khap-linked resolution to draw endorsement from.",
    "This Archive was not able to identify any woman named among the organisers, presiding figures, attending dignitaries, or endorsing civic leaders in the reporting reviewed. That is consistent with the pattern already documented in [this Archive's account of khap leadership and the parallel mahila khap structure](/research/khap-panchayat-system): the office of presiding leadership in these bodies remains, in the reporting available, male, even as attendance and geographic reach expand in other directions.",

    "## What Was Actually Resolved",
    "The resolutions are unusually specific, fixing exact figures for gifts, headcounts and expenditure at each stage of a wedding rather than issuing general appeals for restraint. Reporting attributes this precision to two earlier mahapanchayats, in 1974 and 2004, whose decisions the organisers said were revisited and updated for present circumstances.",
    "On engagement (sagai): the groom is to receive only one rupee, five garments and one kilogram of sweets, with a maximum of five people attending from the groom's side. On the pregnancy ceremony (godh bharai): a maximum of five women and five men, with the expectant woman given one ring, one set of clothing and one kilogram of sweets. On the lagan ritual: only two people from the bride's side deliver the invitation, carrying one rupee, five garments, puffed-rice sweets and a coconut for the groom. On the bhaat ritual: a maximum of eleven women deliver invitations, each given 101 rupees in return, and a maximum of eleven people bring gifts, capped at one tola of gold, 100 grams of silver, clothing and 101 rupees placed on the ceremonial plate.",
    "On the wedding itself: the baraat is capped at 51 people, the meal is to be strictly vegetarian with paneer and khoya-based preparations excluded, and no more than 1,100 rupees is to be given at any individual ritual within the ceremony. Dowry (recorded in reporting under the term kanyadan) is capped at 11,000 rupees in cash, alongside eleven vessels, family clothing, one trunk, one wardrobe, one bed, two tolas of gold and 100 grams of silver -- with no additional cash, goods or vehicle to be given at the bride's departure beyond these fixed items. Alcohol, DJ music and non-vegetarian food are prohibited outright at weddings and other social functions.",
    "On death observances: the death feast (mrityu bhoj) is banned entirely, with only tea, water or light refreshment permitted according to season; a family may instead hold a memorial reading (katha) one year after the death if it chooses.",
    "To oversee compliance, the mahapanchayat resolved to constitute committees at three levels: a village-level committee of the 36 biradaris meeting every three months, empowered to mediate small disputes between couples and families before they escalate; a pal-level committee meeting every six months; and a central committee of 52 members, one from each pal, meeting annually. Reporting states that families found not to comply with the resolutions are to face social boycott -- exclusion of the community from that family's functions -- which is [the characteristic sanction of khap-derived bodies documented elsewhere on this Archive](/research/khap-panchayat-system), since such bodies possess no coercive or legal authority beyond the willingness of member villages to observe their decisions.",

    "## What Was on the Agenda Beforehand, and What Was Not Resolved",
    "The pre-event announcement on 3 September had signalled a wider agenda than the resolutions ultimately published: alongside wedding and funeral expenditure, organisers said they intended to address rising drug use, gambling, and hooliganism or public disorder. None of the reporting on the resolutions actually passed records a specific decision on drugs, gambling or public order in the terms the announcement suggested, though the general prohibition on alcohol at social functions and the emphasis on curbing disorder implicit in the Minister's remarks may be read as a partial response to that stated concern.",
    "This Archive specifically checked whether the Mandkola resolutions addressed mobile phone use, women's clothing, how girls sit on two-wheelers, or love marriage -- questions that dominated coverage of [the Naugama Khap meetings at Ramrai in August 2026](/research/khap-panchayat-2026). No such resolution appears in the reporting reviewed for this article. Readers should not assume that because one khap-linked mahapanchayat took up a given issue, all such gatherings do; the record needs to be checked event by event, which is the same caution [this Archive's account of the Ramrai meetings](/research/khap-panchayat-2026) applies in the other direction.",

    "## Reading Mandkola Against the Wider Record",
    "Mandkola's resolutions sit squarely within the pattern of socially conservative, reform-directed decision-making already documented across khap and pal bodies in 2026: restrictions on wedding extravagance and alcohol at the Meham sarva khap mahapanchayat in July, and now, at far greater specificity, at Mandkola in September. Where Mandkola differs from the Ramrai meetings is composition and reception. Ramrai's most-reported decisions concerned individual conduct -- a remark about how a girl should sit on a motorcycle -- and drew sustained pushback from younger residents on social media. Mandkola's decisions concern collective ritual expenditure, and drew public endorsement from a wide range of civic and professional bodies rather than the youth backlash documented at Naugama. Whether that reflects a genuine difference in how these two categories of decision are received, or simply a difference in what social media chose to amplify, is not something this Archive can settle from the reporting available, and it is exactly the kind of question the documentation programme discussed [in this Archive's structural account of khap institutions](/research/khap-panchayat-system) exists to investigate properly.",
    "The three-tier committee Mandkola has constituted -- village, pal, and a 52-member central body -- is worth setting against the classical hierarchy described in that same article: kunbha, thola, panna, village, ganwand, thamba, khap, Sarv Khap. The Mandkola structure is not identical to that hierarchy; it is a purpose-built compliance mechanism layered onto the existing pal federation, meeting on a fixed schedule rather than convening only when a dispute escalates. Whether such standing committees represent a durable evolution of how these bodies enforce their decisions, or a one-off structure that lapses once the immediate mobilisation around this mahapanchayat fades, is a question only future documentation can answer.",

    "## Conclusion",
    "Mandkola on 6 September 2026 was, on the evidence reviewed, a large and specifically drafted mahapanchayat, attended by a sitting state minister, a serving MLA, and senior former officeholders, and organised on an explicitly inter-community and inter-faith basis broader than most khap-linked gatherings documented this year. Its resolutions are exceptionally precise on the economics of marriage and death ritual, and it has built a standing three-tier structure to review compliance over the coming year. What it did not do, on the record available, is take up the questions of personal conduct -- phones, clothing, how women travel -- that made the Ramrai meetings a month earlier a national story. Reading Mandkola and Ramrai together, rather than treating either as representative of what these institutions generally decide, is the discipline this Archive has argued for throughout its coverage of khap and pal panchayats in 2026.",
  ],
  sources: [
    "Amar Ujala. Delhi NCR: 6 सितंबर को मंडकोला में होगी सर्व खाप, सर्वजातीय, सर्वधर्म महापंचायत. 3 September 2026. https://www.amarujala.com/delhi-ncr/a-sarv-khap-sarva-jatiya-and-sarva-dharma-mahapanchayat-will-be-held-in-mandkola-on-september-6-delhi-ncr-news-c-25-1-mwt1001-115175-2026-09-03 (pre-event announcement: organisers' description of the gathering as Sarv Khap, sarvajatiya and sarvadharma; Dharmveer Dagar and Tayyab Hussain Ghasediya as organisers; invitations extended from Delhi to Agra and Aligarh; stated agenda including drugs, gambling and public disorder).",
    "Amar Ujala. 52 पालों की महापंचायत के बड़े फैसले: बरात में मांसाहार पर रोक, शामिल होंगे 51 लोग, शादी में नहीं होगा पनीर. 6 September 2026. https://www.amarujala.com/haryana/palwal/major-decisions-by-the-mahapanchayat-of-52-paals-ban-on-non-vegetarian-food-at-wedding-processions-2026-09-06 (principal source for the full list of resolutions -- engagement, godh bharai, lagan, bhaat, wedding and dowry limits, death-feast ban, DJ and alcohol ban -- the three-tier committee structure and review schedule, and named attendees Gaurav Gautam, Uday Bhan, Raghuveer Singh Tewatia, Karan Singh Dalal, Praveen Dagar and Vinod Sharma).",
    "Amar Ujala. Palwal News: 52 पाल महापंचायत में कुरीतियों पर कसा शिकंजा. 8 September 2026. https://www.amarujala.com/haryana/palwal/crackdown-on-social-evils-at-the-52-pal-mahapanchayat-palwal-news-c-25-1-mwt1001-115278-2026-09-08 (detailed restatement of the ritual-by-ritual gift and expenditure limits).",
    "Amar Ujala. Palwal News: 52 पालों की महापंचायत में लिए गए निर्णय का स्वागत. 8 September 2026. https://www.amarujala.com/haryana/palwal/decision-taken-at-the-mahapanchayat-of-the-52-palas-welcomed-palwal-news-c-24-1-pal1008-127833-2026-09-08 (public endorsement of the resolutions by the presidents of the district Bar Association, a farmers' front, a trade federation, an employees' union, the local Jain community and a garment traders' association).",
    "Desh Rojana. Palwal News: गौरव गौतम की मौजूदगी में 52 पाल महापंचायत का बड़ा फैसला, विवाह समारोहों में फिजूलखर्ची पर लगेगी रोक. https://www.deshrojana.com/haryana/palwal/palwal-news-big-decision-of-52-pal-mahapanchayat-in-the/article-4147 (Gaurav Gautam's attendance and his quoted remark that development alone is insufficient without curbing social evils and unnecessary expenditure).",
    "The Haryana Story. Know Your Minister -- Gaurav Gautam, Youngest Minister in Saini Cabinet. https://en.theharyanastory.com/article/1853/know-your-minister-gaurav-gautam-youngest-minister-in-saini-cabinet (Gaurav Gautam's exact portfolio: Minister of State, Youth Empowerment and Entrepreneurship (Independent Charge), Sports (Independent Charge) and Law and Legislative Affairs (Attached); MLA for Palwal since 2024).",
    "GROUND REPORT (unverified) -- The identification of \"Praveen Dagar\" as a former MLA in Amar Ujala's 6 September report is noted alongside other public information identifying a Praveen Dagar as the sitting MLA for the neighbouring Hathin constituency. This Archive has not established whether these refer to the same individual, and records the discrepancy rather than resolving it.",
  ],
};

export default MandkolaMahapanchayat2026;
