const PhogatKhapPanchayat2026 = {
  body: [
    "## Introduction",
    "On 13 September 2026, the Sarvajaatiya Phogat Khap held a panchayat at Baba Swami Dayal Dham in Charkhi Dadri, Haryana, presided over by khap president Suresh Phogat. This account draws on two things together: a ground report from the gathering itself, relayed to this Archive by an attendee, and the one independently published account this Archive was able to locate covering the same date and venue. The two overlap on the meeting's opening business and diverge on how much of the rest was reported publicly, which is itself worth documenting rather than smoothing over.",
    "The panchayat's reported agenda ran considerably wider than what published coverage of this specific date captured. Rather than treat that gap as a reason to doubt the ground report, this article sets out what each source independently supports, and places the wider agenda alongside a genuinely active regional pattern of near-identical resolutions passed by other khaps in the weeks immediately before and after 13 September. Read together, the picture is one of a panchayat whose substance sits comfortably within a documented regional wave, even where a single published article did not itself record the full agenda.",

    "## What Independent Reporting Confirms",
    "Published coverage of 13 September 2026 confirms the opening of the panchayat: a tribute meeting at Baba Swami Dayal Dham honouring farmers who lost their lives during the Jat Reservation Agitation. The organising body is named as the Sarvajaatiya Phogat Khap, meaning the all-community Phogat Khap, with Suresh Phogat presiding as president and Kuldeep Phogat named as khap secretary, alongside executive committee members and representatives from all five neighbourhoods of Dadri. Phogat is quoted describing the farmers' sacrifice as a message of courage, struggle and duty to coming generations, and their remembrance as society's collective responsibility.",
    "The sarvajaatiya naming is worth pausing on. It is the same widening of khap membership beyond a single founding clan that [this Archive's study of khap structure](/research/khap-panchayat-system) sets out in detail, and the same term the organisers of the Mandkola mahapanchayat used to describe their own gathering that same month. A reader encountering sarvajaatiya khaps in three separate 2026 reports within weeks of each other should read that as the same structural development recurring, not as three unrelated institutions coincidentally choosing the same word.",

    "## The Ground Report: What Was Reportedly Resolved",
    "Beyond the tribute, the ground report relayed to this Archive describes a substantially fuller agenda, recorded here as a ground account rather than as independently verified published fact.",
    "On music and public conduct, the khap is reported to have opposed songs glorifying weapons and violence, explicitly rejecting the term gun culture for what it called gand culture instead, a deliberate pun turning gun into gand, meaning filth. The khap is reported to have demanded government action or a ban against songs and artists it regards as promoting weapons and crime, on the ground that such content pushes young people toward criminal behaviour.",
    "On marriage and relationships, the khap is reported to have taken four positions: non-acceptance of live-in relationships within its area, framed as inconsistent with social and family propriety; opposition to marriage within the same gotra; a requirement that love marriages proceed only with the full consent of both sets of parents, framed as consistent with the social order rather than opposed to love marriage as such; and opposition to same-sex marriage. This last point carries its own caveat directly from the ground report itself: it appears only in the account relayed to this Archive, no separately published written resolution or press release confirming it independently has been located, and it should accordingly be read as a reported position rather than a verified formal resolution.",
    "On drugs, the khap is reported to have appealed to young people to stay away from intoxicants, framed the drug trade as a serious threat to youth and society, and pledged cooperation with police and district administration against drug traffickers and anti-social elements, alongside a call for a wider social movement against drug use across Haryana.",

    "## Where This Sits in the Wider Record",
    "None of the themes in the ground report appear out of nowhere. Each has a documented parallel elsewhere in the record this Archive has been assembling through 2026, and setting them side by side supports rather than undercuts the ground report's substance.",
    "The Phogat Khap's own position on music and live-in relationships did not originate on 13 September. In late March 2025, at the same venue and under the same president, the khap publicly opposed gun culture and obscenity in Haryanvi songs and raised concerns about live-in relationships, warning that khaps would unite for larger action if the government failed to respond. A panchayat restating and updating an eighteen-month-old position at its own memorial gathering is an entirely ordinary thing for a standing institution to do, and it is consistent with, not contradicted by, the ground report describing the same stance again in September 2026.",
    "The marriage-related positions in the ground report track closely with resolutions passed by other khaps in the same district in the weeks immediately before. On 21 August 2026, Majra Khap at Rupgarh village in Jind district, under president Gurvinder Singh Sindhu, resolved against live-in relationships, required parental consent for love marriage, renewed the demand for restrictions on same-gotra marriage, and called for legal change regarding same-sex marriage, alongside action against drug dealers and fines for obscene songs at weddings. On 9 August 2026, a khap conference at Kandela in Jind resolved to form village-level committees against drugs and against what it too called gand culture. Three khap gatherings within five weeks of each other, across two adjoining districts, converging on the same handful of positions and even the same wordplay, is a genuine regional pattern rather than a coincidence, and it is the kind of pattern [this Archive has traced before](/research/khap-panchayat-2026) in the run of 2026 mahapanchayats addressing gun culture, obscenity and intoxicants, including the Meham Chaubisi gathering in July.",
    "None of this proves that every specific line of the ground report was passed as a formal resolution in the precise words recorded. What it does establish is that the ground report describes positions that fit, in substance and often in phrasing, a documented wave of khap decision making running through August and September 2026 in exactly this part of Haryana, which is the strongest kind of corroboration available for an account this Archive was not able to independently source in full through published reporting.",

    "## What This Panchayat Is Not Reported to Have Decided",
    "The ground report relayed to this Archive was explicit about the limits of what it could confirm, and that caution is preserved here rather than smoothed over. It does not describe, and no published source locates, any decision at this Phogat Khap panchayat restricting mobile phone use, prescribing what girls may wear, restricting how anyone may sit on a motorcycle or travel by vehicle, banning hookah, banning DJ music at weddings specifically, capping dowry amounts or baraat headcounts, prohibiting alcohol, authorising social boycott or a monetary fine as a sanction, or claiming any authority to annul a marriage or punish a couple.",
    "Several of these items are documented khap decisions, but elsewhere. Baraat headcounts and detailed wedding gift limits were resolved at [the Mandkola mahapanchayat](/research/mandkola-mahapanchayat-2026) that same September. A remark about how a girl should sit on a motorcycle, and the youth backlash it produced, belong to [the Naugama Khap meetings at Ramrai](/research/khap-panchayat-2026) in August. Reading about any of those elsewhere and attaching them to this Phogat Khap panchayat as well would be exactly the kind of conflation this Archive's coverage of khap panchayats in 2026 has repeatedly warned against, in both directions: neither importing a stricter record than the evidence supports, nor discounting a ground report because a single published article did not happen to cover its full scope.",

    "## Why the Distinction Matters",
    "A khap decides for itself. [Nothing in the institution's structure gives one khap's resolution binding force over another](/research/khap-panchayat-system), and nothing entitles an outside observer to average several khaps' positions into one composite account of what any single one of them decided. The Phogat Khap panchayat of 13 September 2026 is properly read as three layered facts rather than one: an independently confirmed memorial tribute, a fuller ground-reported agenda that fits a documented regional pattern without being independently published in full, and a specific list of things this panchayat is not reported to have addressed at all, however often those same items appear in coverage of other khaps.",
    "Precision of this kind is not a formality. It is what allows a ground report from a single attendee to be treated as evidence rather than rumour, and it is what stops the accurate, independently confirmed decisions of one khap from being diluted by, or wrongly credited with, the decisions of another. Documenting institutions of this kind accurately, panchayat by panchayat and date by date, remains the precondition for any criticism or defence of them that is actually worth making.",
  ],
  sources: [
    "Amar Ujala. Charkhi Dadri News: Tribute meeting today in memory of farmers who lost their lives in the Jat Reservation Agitation. 13 September 2026. https://www.amarujala.com/haryana/charkhi-dadri/tribute-meeting-today-in-memory-of-farmers-who-lost-their-lives-in-the-jat-reservation-agitation-charkhi-dadri-news-c-126-1-shsr1012-160248-2026-09-13 (Sarvajaatiya Phogat Khap tribute meeting at Baba Swami Dayal Dham, Charkhi Dadri; Suresh Phogat presiding, Kuldeep Phogat as khap secretary; note that this outlet's own transliteration renders the name as Fogat, one of several English spellings used across sources for the Hindi फोगाट, alongside Fogaat and Phogat).",
    "Punjab Kesari (Haryana edition). Gun culture, obscenity: Phogat Khap came out in protest against gun culture. 27 March 2025. https://haryana.punjabkesari.in/haryana/news/phogat-khap-came-out-in-protest-against-gun-culture-2126126 (Sarvajaatiya Phogat Khap, Swami Dayal Dham, Charkhi Dadri; Suresh Phogat presiding; opposition to gun culture and obscenity in Haryanvi songs, live-in relationships, and concern over love marriage; establishes this as the khap's standing position eighteen months before the September 2026 gathering, not a position first taken there).",
    "ETV Bharat. Demand for a ban on Haryanvi songs promoting gun culture, Charkhi Dadri Phogat Khap panchayat. 28 March 2025. https://www.etvbharat.com/hi/!state/charkhi-dadri-phogat-khap-demands-ban-haryanvi-songs-gun-culture-in-haryana-khap-panchayat-haryana-news-hrs25032801496 (corroborates the March 2025 date, venue and content of the gun-culture and live-in position; quotes Suresh Phogat).",
    "Amar Ujala. Jind News: Haryana khap opposes live-in relationships but accepts love marriages. 21 August 2026. https://www.amarujala.com/haryana/jind/haryana-khap-opposes-live-in-relationships-but-accepts-love-marriages-2026-08-21 (Majra Khap, Rupgarh village, Jind district; Gurvinder Singh Sindhu presiding, with Mahendra Singh Saharan as general secretary; resolutions on live-in relationships, parental consent for love marriage, same-gotra marriage restriction, a legal-change demand on same-sex marriage, action against drug dealers, and fines for obscene wedding songs; a different khap, district and date from the Phogat Khap panchayat, presented here as the closest documented parallel to the marriage-related items in the ground report).",
    "Dainik Tribune. Jind News: Khaps to form village-to-village committees against drugs and gand culture; Kandela conference passes resolution condemning Kangana Ranaut's statement. 9 August 2026. https://www.dainiktribuneonline.com/news/haryana/jind-news-khaps-to-form-village-to-village-committees-against-drugs-and-filth-culture-kandela-conference-passes-resolution-condemning-kangana-ranauts-statement/ (Kandela conference, Jind; anti-drug village committees and the gand culture framing, corroborating that this wordplay and this drug-committee approach were current across regional khap gatherings in the weeks before 13 September 2026).",
    "GROUND REPORT (community account): The full agenda of the 13 September 2026 Phogat Khap panchayat beyond the tribute: opposition to gun culture, reframed by the khap as gand culture; non-acceptance of live-in relationships; opposition to same-gotra marriage; a parental-consent requirement for love marriage; opposition to same-sex marriage, itself further flagged within the ground report as lacking a separately confirmed written resolution; an anti-drug appeal to youth; and a pledge of cooperation with police and district administration against drug trafficking. Relayed to this Archive by an attendee; not confirmed in the published reporting reviewed for this article beyond the tribute itself.",
  ],
};

export default PhogatKhapPanchayat2026;
