const PhogatKhapPanchayat2026 = {
  body: [
    "## Introduction",
    "On 13 September 2026, the Sarvajaatiya Phogat Khap held a panchayat at Baba Swami Dayal Dham in Charkhi Dadri, Haryana, presided over by khap president Suresh Phogat. This article records what the panchayat opened with and what it resolved, and then sets those decisions alongside the wider record of khap panchayats this Archive has been documenting through 2026, because a single khap's decisions are best read in that context rather than in isolation.",

    "## What the Panchayat Resolved",
    "The panchayat opened with a tribute at Baba Swami Dayal Dham to the farmers who lost their lives during the Jat Reservation Agitation, attended by Suresh Phogat, khap secretary Kuldeep Phogat, the executive committee, and representatives from all five neighbourhoods of Dadri. Phogat described the farmers' sacrifice as a message of courage, struggle and duty to coming generations, and their remembrance as society's collective responsibility.",
    "On music and public conduct, the khap opposed songs glorifying weapons and violence, rejecting the term gun culture in favour of what it called filth culture instead, and demanded government action against songs and artists it regards as promoting weapons and crime on the ground that such content pushes young people toward criminal behaviour.",
    "On marriage and relationships, the khap took four positions:",
    "::list:Non-acceptance of live-in relationships within its area, as inconsistent with social and family propriety.|Opposition to marriage within the same gotra.|A requirement that love marriages proceed only with the full consent of both sets of parents, framed as consistent with the social order rather than opposed to love marriage as such.|Opposition to same-sex marriage, an item carried in media coverage of the panchayat though no separately published written resolution on it has been located independently, and recorded here with that qualification rather than as a formally confirmed text.",
    "On drugs, the khap appealed to young people to stay away from intoxicants, described the drug trade as a serious threat to youth and society, and pledged cooperation with police and district administration against drug traffickers and anti-social elements, alongside a call for a wider social movement against drug use across Haryana.",
    "The sarvajaatiya naming is worth noting in its own right. It is the same widening of khap membership beyond a single founding clan that [this Archive's study of khap structure](/research/khap-panchayat-system) sets out in detail, and the same term the organisers of the Mandkola mahapanchayat used to describe their own gathering that same month. Three sarvajaatiya khaps surfacing in 2026 reporting within weeks of each other reflects the same structural development recurring, not three unrelated institutions coincidentally choosing the same word.",

    "## Regional Context",
    "The Phogat Khap's position on music and live-in relationships did not originate on 13 September. In late March 2025, at the same venue and under the same president, the khap publicly opposed gun culture and obscenity in Haryanvi songs and raised concerns about live-in relationships, warning that khaps would unite for larger action if the government failed to respond. The September 2026 panchayat restates and updates a position the khap has held consistently for eighteen months.",
    "The marriage-related positions also sit within a wider regional pattern from the same weeks. On 21 August 2026, Majra Khap at Rupgarh village in Jind district, under president Gurvinder Singh Sindhu, resolved against live-in relationships, required parental consent for love marriage, renewed the demand for restrictions on same-gotra marriage, and called for legal change regarding same-sex marriage, alongside action against drug dealers and fines for obscene songs at weddings. On 9 August 2026, a khap conference at Kandela in Jind resolved to form village-level committees against drugs and what it too called filth culture. Three khap gatherings within five weeks of each other, across two adjoining districts, converging on the same positions and the same reframing of gun culture as filth culture, place the Phogat Khap panchayat within an active regional wave rather than as an isolated event, the kind of pattern [this Archive has traced before](/research/khap-panchayat-2026) across the run of 2026 mahapanchayats addressing gun culture, obscenity and intoxicants, including the Meham Chaubisi gathering in July.",

    "## Conclusion",
    "A khap decides for itself. [Nothing in the institution's structure gives one khap's resolution binding force over another](/research/khap-panchayat-system), and the Phogat Khap panchayat of 13 September 2026 should be read on its own record: a memorial tribute, and a set of resolutions on music, marriage and drugs consistent with the khap's own established positions and with a wider regional pattern this year. Documenting each panchayat this specifically, khap by khap and date by date, is what this Archive's coverage of khap institutions in 2026 has aimed for throughout.",
  ],
  sources: [
    "Author's account of proceedings at the Phogat Khap panchayat, Baba Swami Dayal Dham, Charkhi Dadri, 13 September 2026.",
    "Amar Ujala. Charkhi Dadri News: Tribute meeting today in memory of farmers who lost their lives in the Jat Reservation Agitation. 13 September 2026. https://www.amarujala.com/haryana/charkhi-dadri/tribute-meeting-today-in-memory-of-farmers-who-lost-their-lives-in-the-jat-reservation-agitation-charkhi-dadri-news-c-126-1-shsr1012-160248-2026-09-13 (Sarvajaatiya Phogat Khap tribute meeting at Baba Swami Dayal Dham, Charkhi Dadri; Suresh Phogat presiding, Kuldeep Phogat as khap secretary; note that this outlet's own transliteration renders the name as Fogat, one of several English spellings used across sources for the Hindi फोगाट, alongside Fogaat and Phogat).",
    "Punjab Kesari (Haryana edition). Gun culture, obscenity: Phogat Khap came out in protest against gun culture. 27 March 2025. https://haryana.punjabkesari.in/haryana/news/phogat-khap-came-out-in-protest-against-gun-culture-2126126 (Sarvajaatiya Phogat Khap, Swami Dayal Dham, Charkhi Dadri; Suresh Phogat presiding; the khap's position on gun culture, obscenity in Haryanvi songs, live-in relationships and love marriage, eighteen months before the September 2026 panchayat).",
    "ETV Bharat. Demand for a ban on Haryanvi songs promoting gun culture, Charkhi Dadri Phogat Khap panchayat. 28 March 2025. https://www.etvbharat.com/hi/!state/charkhi-dadri-phogat-khap-demands-ban-haryanvi-songs-gun-culture-in-haryana-khap-panchayat-haryana-news-hrs25032801496 (the March 2025 date, venue and content of the gun-culture and live-in position; quotes Suresh Phogat).",
    "Amar Ujala. Jind News: Haryana khap opposes live-in relationships but accepts love marriages. 21 August 2026. https://www.amarujala.com/haryana/jind/haryana-khap-opposes-live-in-relationships-but-accepts-love-marriages-2026-08-21 (Majra Khap, Rupgarh village, Jind district; Gurvinder Singh Sindhu presiding, with Mahendra Singh Saharan as general secretary; resolutions on live-in relationships, parental consent for love marriage, same-gotra marriage restriction, a legal-change demand on same-sex marriage, action against drug dealers, and fines for obscene wedding songs).",
    "Dainik Tribune. Jind News: Khaps to form village-to-village committees against drugs and filth culture; Kandela conference passes resolution condemning Kangana Ranaut's statement. 9 August 2026. https://www.dainiktribuneonline.com/news/haryana/jind-news-khaps-to-form-village-to-village-committees-against-drugs-and-filth-culture-kandela-conference-passes-resolution-condemning-kangana-ranauts-statement/ (Kandela conference, Jind; anti-drug village committees and the filth culture framing, this outlet's own English rendering of the same term).",
  ],
};

export default PhogatKhapPanchayat2026;
